### ISSUE TITLE
Build/Install Documentation

### ISSUE THREAD

**Issue by samuelcomeau6** [danselmi/cbGcov#1]
Hello, can you please provide some modest direction of how to install this plugin. It's not apparent to someone who isn't a master of CodeBlocks.

**Comment by danselmi** [comment]
On what platform do you like to install it?

**Comment by samuelcomeau6** [comment]
I was trying to install it on windows. Do you need to install the CodeBlocks sdk? Just a few sentences on how to install it would be really helpful.
